Display setting
bitcoin-core/gui-qml pull request #311
Opened 2023-03-31 10:15 UTC by jarolrod

Based on https://github.com/bitcoin-core/gui-qml/pull/310 and https://github.com/bitcoin-core/gui-qml/pull/306

This moves "Display" related settings into a new "Display" page. Also sets up QSettings wiring for options.

[![Windows](https://img.shields.io/badge/OS-Windows-green)](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/unsecure_win_gui.zip?branch=pull/<PR>)
[![Intel macOS](https://img.shields.io/badge/OS-Intel%20macOS-green)](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/unsecure_mac_gui.zip?branch=pull/<PR>)
[![Apple Silicon macOS](https://img.shields.io/badge/OS-Apple%20Silicon%20macOS-green)](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/unsecure_mac_arm64_gui.zip?branch=pull/<PR>)
[![ARM64 Android](https://img.shields.io/badge/OS-Android-green)](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/unsecure_android_apk.zip?branch=pull/<PR>)

2023-04-10 03:39 UTC, johnny9 requested changes
Concept ACK. I like the functionality here. Noticed some minor things when reviewing.

2023-04-10 03:39 UTC, johnny9 commented on src/qml/components/ThemeSettings.qml
> +// Copyright (c) 2022 The Bitcoin Core developers
2023 now

2023-04-10 03:39 UTC, johnny9 commented on src/qml/components/BlockClockSizeSettings.qml
> +}
No newline at end of file

2023-04-10 03:39 UTC, johnny9 commented on src/qml/components/BlockClockSizeSettings.qml
> +// Copyright (c) 2022 The Bitcoin Core developers
2023

2023-04-10 03:39 UTC, johnny9 commented on src/qml/components/ThemeSettings.qml
> +}
No newline at end of file

2023-04-10 03:39 UTC, johnny9 commented on src/qml/components/blockclockdial.cpp
> +#include <QtGlobal>
Is this a needed import?

2023-04-10 03:39 UTC, johnny9 commented on src/qml/pages/settings/SettingsBlockClockSize.qml
> +}
No newline at end of file

2023-04-10 03:39 UTC, johnny9 commented on src/qml/pages/settings/SettingsDisplay.qml
> +}
No newline at end of file

2023-04-12 13:05 UTC, GBKS commented
I have to say, this doesn't feel right. Having to go several screens into settings to adjust the size only having to go back to see what it looks like is just not right. And the big one is so huge on desktop that it looks a bit crazy.

Could we also toggle through the sizes via a simple double-tap on the clock? It does require that the UI can differentiate between single and double-taps, not sure if that's built-on or some custom functionality.

Here's a quick mock-up with some ideas (icons are placeholders). I reframed this as two display modes. One is for active use, the other is called "Showcase". Each has an explainer. For "Showcase", there might be other things we may want to tweak, like hiding the Settings button until you interact with the screen. It could also be cool if the big one renders with more detail, more animations or other unique treatments rather than just being bigger.

![image](https://user-images.githubusercontent.com/695901/231466372-4818abc8-e27c-4599-804b-a8576231fe34.png)


![image](https://user-images.githubusercontent.com/695901/231464869-b5dea801-c605-4d8b-aed7-9b3b740ca32f.png)

2023-04-18 03:41 UTC, jarolrod commented on src/qml/components/blockclockdial.cpp
> +#include <QtGlobal>
seems not

2023-04-18 05:07 UTC, jarolrod commented
Updated from [7626d1f ](https://github.com/bitcoin-core/gui-qml/commit/7626d1fd41d3e2d7ad8896c3085db4718320c3b7)to [fd00969](https://github.com/bitcoin-core/gui-qml/commit/fd00969972e8458182fab2c9084183489494b831), [compare](https://github.com/bitcoin-core/gui-qml/compare/7626d1fd41d3e2d7ad8896c3085db4718320c3b7..fd00969972e8458182fab2c9084183489494b831)

Changes: addressed review feedback

@GBKS I've integrated your suggestion on the "Block Clock display mode" page. But, I've left out the icon until we get an official svg for it. I've also left out the text that you can double tap on the clock; that will be introduced in the followup that implements double tap detection. I've also left out the last sentence in the `Showcase` option until that functionality is actually introduced.

The values for default and showtime could use review.

2023-04-20 21:12 UTC, jarolrod commented
Updated from from [fd00969 ](https://github.com/bitcoin-core/gui-qml/commit/fd00969972e8458182fab2c9084183489494b831)to [753d052](https://github.com/bitcoin-core/gui-qml/commit/753d052b4c055559c06023dd7ce781909e3bb51e)

Changes: default is now 1/3 as declared by the based on PR, and display is now 1/2. We can fine tune these values later

2023-04-21 04:34 UTC, johnny9 commented
ACK 753d052b4c055559c06023dd7ce781909e3bb51e

2023-04-21 08:36 UTC, GBKS commented
Tested and looks good. I slightly tweaked the icons and made them export ready, find them [in Figma here](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=7037%3A194740&t=Kg56pL8DUnTjAgEK-1).

![image](https://user-images.githubusercontent.com/695901/233587629-85d919c2-67b4-4fd3-b8b1-3c90dab94915.png)

What do you think of changing "Default" to "Compact"?

Could you also please put the page title in the title bar rather than in the page itself?

And another question about casing. I always use sentence case in design, but I see a good amount of title case in the application. Let's decide on something (obviously I'd go for sentence case). What's your take?

1/2 still feels a tad OP, but let's run with it and see if we want to tweak it after a bit of usage.

2023-04-23 06:14 UTC, jarolrod commented
Updated from from [753d052 ](https://github.com/bitcoin-core/gui-qml/commit/753d052b4c055559c06023dd7ce781909e3bb51e)to [b59654c](https://github.com/bitcoin-core/gui-qml/commit/b59654c62aab9c9dcc008510175c7af9bd56dcd8), [compare](https://github.com/bitcoin-core/gui-qml/compare/753d052b4c055559c06023dd7ce781909e3bb51e..b59654c62aab9c9dcc008510175c7af9bd56dcd8)

Changes:
- update to new centered bitcoin icon
- introduced and use block clock display mode icons

2023-04-23 06:17 UTC, jarolrod commented
@GBKS as shown in the new PR description images, should the Display settings page itself have a title bar?

2023-04-28 09:25 UTC, GBKS commented
Yes sir, just "Settings".

2023-05-10 01:01 UTC, jarolrod commented
Updated [b59654c ](https://github.com/bitcoin-core/gui-qml/commit/b59654c62aab9c9dcc008510175c7af9bd56dcd8)to [410b135](https://github.com/bitcoin-core/gui-qml/commit/410b135ea0c2a0b8e90e0cc8bfdf5d8963f56f7d)

changes: rebased over main

2023-05-10 01:50 UTC, jarolrod commented
Updated from [410b135 ](https://github.com/bitcoin-core/gui-qml/commit/410b135ea0c2a0b8e90e0cc8bfdf5d8963f56f7d)to [b0f7265](https://github.com/bitcoin-core/gui-qml/commit/b0f7265fdcf021605a1e20c135935aec48e4c242)

changes: added "Settings" title to the display settings page

2023-05-29 02:59 UTC, jarolrod commented
cc @GBKS @mouxdesign CI artifacts are built and this can be tested now

2023-05-31 03:47 UTC, jarolrod commented
Updated from b0f7265 to af0ddf6, rebased over main

2023-05-31 15:15 UTC, johnny9 approved these changes
ACK af0ddf69e4a9bc75b3b61a4d31cc086ba26b6377

Updates look good, no qml errors.

2023-05-31 15:40 UTC, merged