UI Only Custom Datadir
bitcoin-core/gui-qml pull request #392
Opened 2024-03-27 19:14 UTC by D33r-Gee

This pull request is a focused iteration of #390, intended to isolate and test the UI frontend elements. Backend functionality has been intentionally excluded to streamline the testing, review, and merge process.

<details>
<summary>Ubuntu Screenshots</summary>

![Screenshot 2024-03-14 124000](https://github.com/bitcoin-core/gui-qml/assets/111142327/a8d8ebbc-c66c-4626-ba7a-630f19c889ae)
![Screenshot 2024-01-29 074759](https://github.com/bitcoin-core/gui-qml/assets/111142327/fea1b72d-2760-436c-aba5-2094b5826fa4)
![Screenshot 2024-01-29 074734](https://github.com/bitcoin-core/gui-qml/assets/111142327/768f93a0-4f9c-46cc-9b31-7d9fcabaaf1e)

</details>

**Prerequisites**

For testing this pull request, ensure you have the following Qt modules installed:

* On Ubuntu 22.04:

```bash
sudo apt-get install qtdeclarative5-dev
sudo apt-get install qtquickcontrols2-5-dev
sudo apt-get install qml-module-qtquick-controls2
sudo apt install qml-module-qtquick-dialogs
```
* For Android:
  * Make sure you delete the prior depends folder (i.e. `depends/aarch64-linux-android`) and rebuild them.

**Implementation Details**

This introduces `FileDialog` class for a user-friendly selection experience.

* **QML Backend**
    * Updated `options_model` files to account for custom data directory configuration and placeholders for custom `datadir` wiring.
    * Added @johnny9 depends patches to allow static building
* **QML Frontend**
    * Updated `StorageLocations.qml` to allow for custom data directory selection.

Follow up PR will add display of the custom `datadir` in StorageSettings.qml

2024-03-28 03:37 UTC, johnny9 requested changes
Update the README at https://github.com/bitcoin-core/gui-qml/tree/main/src/qml with the additional packages that need to be installed.

2024-03-28 03:37 UTC, johnny9 commented on src/qml/components/StorageLocations.qml
> +}
add newline to end of file

2024-03-28 16:20 UTC, D33r-Gee commented on src/qml/components/StorageLocations.qml
> +}
done

2024-03-28 16:44 UTC, D33r-Gee commented
> Update the README at https://github.com/bitcoin-core/gui-qml/tree/main/src/qml with the additional packages that need to be installed.

Good call @johnny9! Just pushed a new commit with the updated doc.

Now it's pretty much equivalent (give and take) with @jarolrod's #273

2024-03-29 00:24 UTC, pablomartin4btc reviewed
tACK 3f564606e36fcd2ade2bdc37d5217563a4c442ee

It works as expected, left some code-related nits.

<details>
<summary>There's a specific case that I <a href="https://github.com/bitcoin-core/gui-qml/pull/390#pullrequestreview-1940546706">mentioned</a> (3rd. bullet point) in the related PR #390, which I now discovered it's due to starting <code>QT</code> desktop and afterwards it's closed run the <code>QML</code> (on the same network env - e.g. <code>-signet</code>). I'll create an issue to discuss the best way to solve it.</summary>

![image](https://github.com/bitcoin-core/gui-qml/assets/110166421/452c1f1d-a02f-4531-b25a-4bb823bce7d5)

</details>

<details>
<summary>nit: 3rd. commit (f3d251fc93fda956cb8cc14b5717c2485db84781) title length could be shorter, as in the <a href="https://github.com/bitcoin-core/gui-qml/pull/390#pullrequestreview-1953852936">mentioned</a> above related PR , so it can be seen at first glance at the commits list without having to click on the <code>...</code>, or during reviewing the "files changed" tab section also trying to select one from the commits list.</summary>

![image](https://github.com/bitcoin-core/gui-qml/assets/110166421/879ba97b-bc53-4bed-85cc-777dccee92d3)

![image](https://github.com/bitcoin-core/gui-qml/assets/110166421/9946a6bc-85f0-4cc8-9374-1e8c997d2e6b)

</details>

2024-03-29 14:56 UTC, D33r-Gee commented on depends/patches/qt/fix_android_controls_file_location.patch
> + # ifndef QT_STATIC
good catch! Done

2024-03-29 15:13 UTC, D33r-Gee commented on src/qml/components/StorageLocations.qml
> +            optionsModel.setCustomDataDirArgs(customDataDir);
good call! Done

2024-04-02 11:21 UTC, MarnixCroes requested changes
double-clicking on `Custom` opens the storage selection in the background.
single-click works ok

[openbackground.webm](https://github.com/bitcoin-core/gui-qml/assets/93143998/5d313a3b-760d-4df2-8c02-eeadefab9274)



649c2a5af80092e4f43497309aafe5785a2b2bdd you added `qml-module-qtquick-dialogs`, the other 3 `qtdeclarative5-dev` `qtquickcontrols2-5-dev` `qml-module-qtquick-controls2` should be added to the instructions as well?

2024-04-02 16:26 UTC, D33r-Gee commented
> double-clicking on `Custom` opens the storage selection in the background. single-click works ok

Thanks @MarnixCroes, good catch... wasn't able to reproduce on WSL Ubuntu 22.04 will look into it...

> [649c2a5](https://github.com/bitcoin-core/gui-qml/commit/649c2a5af80092e4f43497309aafe5785a2b2bdd) you added `qml-module-qtquick-dialogs`, the other 3 `qtdeclarative5-dev` `qtquickcontrols2-5-dev` `qml-module-qtquick-controls2` should be added to the instructions as well?

those are actually found here in the qml/README.md:
https://github.com/bitcoin-core/gui-qml/blob/649c2a5af80092e4f43497309aafe5785a2b2bdd/src/qml/README.md?plain=1#L66
and here:
https://github.com/bitcoin-core/gui-qml/blob/649c2a5af80092e4f43497309aafe5785a2b2bdd/src/qml/README.md?plain=1#L73

2024-04-04 03:40 UTC, johnny9 approved these changes
ACK 649c2a5af80092e4f43497309aafe5785a2b2bdd

Tested static mobile and desktop builds as well as dynamic linux builds and the FileDialog triggers properly with no QML errors.

2024-04-05 22:27 UTC, pablomartin4btc approved these changes
tACK 649c2a5af80092e4f43497309aafe5785a2b2bdd

I've managed to reproduce the [issue reported](https://github.com/bitcoin-core/gui-qml/pull/392#pullrequestreview-1973457090) by @MarnixCroes, on Ubuntu 22.04 it takes a 3 or 4 attempts, but eventually, it occurs. Tried to fix it using `visible: true`/ `false` but couldn't solve it, it would require more investigation and could be done on a follow-up.

nits (not blockers):
- Since this is UI only changes, I'd leave commit ffd5201754e3ebd32d384406de95261116e30f61 out, it doesn't change anything in terms of user experience and if we find an issue there, we'd need to revert it (or fix it on top). So in `StorageLocations.qml` I'd comment the lines making those calls to the `optionsModel` adding another comment on top of each like "`// TODO when model supports it`" or similar.
- I'd make the new custom datadir path selected from the file dialog visible in 2 places: 
  - under the custom datadir field as it's shown in [figma](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?type=design&node-id=7635-19847&mode=design&t=biKXVMD1wrMD6oth-0):

     ![image](https://github.com/bitcoin-core/gui-qml/assets/110166421/6330eb93-6044-47c2-bd2b-7775efa40a63)

  - somewhere in the "Storage settings" page but after onboarding process I think (this definitely as a follow-up) but this needs to be discussed with designers (#bitcoin-core-app channel on "Bitcoin Design" discord) because I don't see any reference in figma (unless I missed it)/ cc: @GBKS. It's important here to mention that would be good also to show here the `-datadir` passed as an argument to QT, which won't be persisted in `Bitcoin-Qt-*.conf` as the custom data dir, or even the default datadir if that's the case (eg on Ubuntu `home/${user}/.bitcoin`) so the user is aware at all times where the data is being taken/ saved at all times.
  
      ![Screenshot from 2024-04-05 16-51-25](https://github.com/bitcoin-core/gui-qml/assets/110166421/4c171f80-d6a1-40d3-b36c-961539a08f97)

2024-04-08 08:04 UTC, merged

2024-04-09 13:57 UTC, GBKS commented
Already merged, but I just tested on Android and MacOS and the UI works fine. Nice work on this, sounds like file picking was quite the heavy lift to get done.

I agree with the UI proposals up there and will prep respective designs.

2024-04-11 07:40 UTC, GBKS commented
I created a follow-up issue for the directory display in storage settings [here](https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/102). Would be great to get your input on the question I have in that issue.